---
abstract: 'Data objects for message board.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  Data::Person: 0
  DateTime: 0
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.59
  Test::MockObject: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Message-Board
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Data::Person: 0
  DateTime: 0
  Mo: 0
  Mo::utils: 0.28
  Readonly: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Data-Message-Board/issues
  homepage: https://github.com/michal-josef-spacek/Data-Message-Board
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Data-Message-Board
version: '0.01'
